Fix unicode issues
bkuhlmann/prawn_plus pull request #3
Opened 2021-04-20 15:46 UTC by alex-ross

Swedish characters like åäö didn't work with prior version. `template.source` is stripped from all unicode characters but `source` is not.

2021-04-20 23:49 UTC, bkuhlmann requested changes
Hey Alexander. :wave: Thanks for catching this. Could you add a corresponding spec for this and amend your commit to adhere to the [Git Lint Style Guide](https://www.alchemists.io/projects/git-lint/#_style_guide)? To see what I mean, run the following locally:

``` bash
bundle exec rake
```

Then you can you correct any errors. Once those two things are in place, I'll be able to accept your changes. :wink:

2021-04-20 23:49 UTC, bkuhlmann commented on lib/prawn_plus/template_handlers/prawn.rb
> +        "pdf = ::Prawn::Document.new;" + source + ";pdf.render;"
:star: Nice find.

2021-04-26 13:22 UTC, alex-ross commented on spec/requests/documents_spec.rb
> +  end
@bkuhlmann here you got some specs. If you revert the actual implementation these will not pass.

2021-04-27 23:53 UTC, bkuhlmann requested changes
There is also a Git Lint violation with this commit that I mentioned earlier which hasn't been addressed yet. When running `bundle exec rake` locally, I see the following error:

``` 
ddf3ae55b6c9946bfee2686d22386f044071aef8 (Alexander Ross, 7 days ago): Fix unicode issues
  Commit Body Line Length Error. Use 72 characters or less per line.
    Line 2: "Swedish characters like åäö didn't work with prior version. `template.source` is stripped from all unicode characters but `source` is not."
  Commit Subject Prefix Error. Use: /Fixed/, /Added/, /Updated/, /Removed/, /Refactored/.
```

If you want, it might be easier for you to fix the commit message and ONLY commit the implementation change. I can add the specs afterwards if you like. This way you'd get credit and I can follow up with the work necessary to keep the code clean. :wink:

2021-04-27 23:53 UTC, bkuhlmann commented on spec/support/dummy/app/controllers/documents_controller.rb
> +  def unicode
:classical_building: Could we use a `UnicodesController#index` for this instead so we are more RESTful?

2021-04-27 23:53 UTC, bkuhlmann commented on spec/support/dummy/config/routes.rb
> +  resources :documents do
:classical_building: Could we use `resources :unicodes` instead so we have a distinct resource/controller for this work separate from the original controller?

2021-04-27 23:53 UTC, bkuhlmann commented on spec/requests/documents_spec.rb
> +  end
Thanks Alexander. Unfortunately, this violates good RSpec testing where _you don't mock what you don't own_. We don't own the `Prawn::Document` object so we shouldn't be mocking it in this case. There is a simpler way to test this. Once unicode characters are added to a PDF, the following error will be triggered (without your fix):

```
ActionView::Template::Error:
  Your document includes text that's not compatible with the Windows-1252 character set.
  If you need full UTF-8 support, use external fonts instead of PDF's built-in fonts.
```

So all we'd really need to do is test for that error.

2021-04-28 21:39 UTC, alex-ross commented on spec/support/dummy/app/controllers/documents_controller.rb
> +  def unicode
I've added a `UnicodesController` now but did split it up for one action per language. Hope that is ok.

2021-04-28 21:43 UTC, alex-ross commented
Response to: https://github.com/bkuhlmann/prawn_plus/pull/3#discussion_r621701725

I changed my spec to not mock anything and expect a successful response instead which will also make sure no errors are thrown.

2021-04-28 21:50 UTC, alex-ross commented
Response to: https://github.com/bkuhlmann/prawn_plus/pull/3#pullrequestreview-646476772

This Git Lint violation does not appear for me. I changed the commit message any way but this is what i get when running `bundle exec rake`.

```
Running Git Lint...
0 commits inspected. 0 issues detected.
Inspecting 4 file(s):
....

0 total warnings
```

Guess there is some configuration on your device here that is not in the this project.

2021-04-29 17:41 UTC, bkuhlmann requested changes
Thanks for folding in the earlier feedback. I think you almost have this and then I can accept your changes. :wink:

Can you also ensure the Git commit is past tense? So use "Fixed" instead of "Fix" which is compatible with the Git Lint style guide.

2021-04-29 17:41 UTC, bkuhlmann commented on spec/support/dummy/app/controllers/unicodes_controller.rb
> +class UnicodesController < ApplicationController
:art: Could we simplify this further by renaming this controller to `UnicodeController` and only adding a `#show` action/method which renders all three languages (since it's possible to add more languages in the future, I suppose). What's more interesting to test here is a PDF which has multiple languages in it which also means you don't have to write so much code. The other bonus is that we maintain a RESTful design which means less code in the routes too (see my comment below which will help illustrate this better).

2021-04-29 17:41 UTC, bkuhlmann commented on spec/support/dummy/config/routes.rb
> +  resource :unicode, only: [] do
:classical_building: I like how you've been able to simplify this. Would you mind using this syntax instead?

``` ruby
resource :unicode, controller: :unicode, only: [:show]
```

This would allow you to have a single RESTful resource which happens to render a PDF for multiple languages with very little code added to the routes.

2021-04-29 17:41 UTC, bkuhlmann commented on spec/requests/unicode_spec.rb
> +  describe "danish" do
:bulb: If you apply my changes mentioned below, should be able to greatly simplify this spec to only testing the `#show` action. For example, I think you'd only need this spec:

``` ruby
describe "#show" do
  it "renders PDF for multiple languages" do
    get unicode_path, headers: {accept: "application/pdf"}
    expect(response).to have_http_status(:ok)
  end
end
```

2021-04-29 18:32 UTC, alex-ross commented
@bkuhlmann updated the code now.

2021-04-30 01:44 UTC, bkuhlmann approved these changes
:star: Thanks for folding in all of the feedback. This is great to have fixed. I'll work on releasing a new version next.

2021-04-30 01:44 UTC, merged